language: generic

services:
  - docker

before_install:
  - docker build -t hnskde/qmongr-base-r .
  - docker run -d -ti --name qmongr-base-r hnskde/qmongr-base-r

script:
  - docker ps | grep -q qmongr-base-r

deploy:
  - provider: script
    script: bash docker_push.sh
    skip_cleanup: true
    on:
      # 'tags: true' maybe added
      branch: master

